### ISSUE TITLE
Confirm a service provider for their event

### ISSUE THREAD

**Issue by Tonkpils** [kaykayyali/plannify.us#7]
# TODO
- [x] In modal, show company info
- [x] Provide back button and confirm button
- [x] Create route for adding vendor services to events
- [x] Use Rails helper to send ajax request and then update the events services modal
- [x] create message model between organizer and vendor
- [x] Send Message during the confirmation of vendor to event
- [x] Display these changes in the confirmed services modal
